services:
  cloud:
    image: cloud
    hostname: cloud
    container_name: cloud
    depends_on:
      - zookeeper
    environment:
      BROKER: redis
      PORT: 6379
      TOPIC: rumble
      URL: https://api.airplanes.live/v2/point/36.1716/-115.1391/200
    networks:
      - aware-network

  redis:
    container_name: redis
    image: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - aware-network

  runway:
    container_name: runway
    image: runway
    ports:
      - 8000:8000
    depends_on:
      - hangar
    networks:
      - aware-network
  
  hangar:
    image: arangodb:latest
    container_name: hangar
    environment:
      ARANGO_ROOT_PASSWORD: arango
    ports:
      - 8529:8529
    volumes:
      - ../hangar/data:/var/lib/arangodb3
      - ../hangar/dumps:/dumps
    networks:
      - aware-network

networks:
  aware-network:
    driver: bridge
    name: aware_network
