services:
  cloud:
    image: cloud
    hostname: cloud
    container_name: cloud
    environment:
      BROKER: redis
      PORT: 6379
      TOPIC: traffic
      URL: https://api.airplanes.live/v2/point/36.1716/-115.1391/200

  redis:
    container_name: redis
    image: redis
    hostname: redis
    ports:
      - 6379:6379

  runway:
    container_name: runway
    image: runway
    ports:
      - 8000:8000
    depends_on:
      - hangar
  
  hangar:
    image: arangodb:latest
    container_name: hangar
    environment:
      ARANGO_ROOT_PASSWORD: arango
    ports:
      - 8529:8529
    volumes:
      - ../hangar/data:/var/lib/arangodb3
      - ../hangar/dumps:/dumps